config/routes.rb
Rails.application.routes.draw do

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  get "/robots.txt" => RobotsGenerator

  get "/sitemap.xml.gz"                        => "sitemap#sitemap", format: :xml
  get "/sitemap/:sitemap_host/generate.xml.gz" => "sitemap#generate", format: :xml, :constraints => { sitemap_host: /[.\-\w]+/ }

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  get "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook
  post '/webhooks/plans' => 'plans#create'
  get '/webhooks/trials' => 'plans#get_trials'

  post '/bounces' => 'amazon_bounces#notification'

  get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  get "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  get "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    post "/prospect_emails" => "marketplaces#create_prospect_email"
  end

  match '/harmony_proxy/*harmony_path' => 'harmony_proxy#proxy', via: :all

  get "/ui_api/topbar_props" => "topbar_api#props"

  get '/_lp_preview' => 'landing_page#preview'

  locale_regex_string = Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES.to_a).join("|")
  locale_matcher = Regexp.new(locale_regex_string)
  locale_matcher_anchored = Regexp.new("^(#{locale_regex_string})$")

  get '/:locale/' => 'landing_page#index', as: :landing_page_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/' => 'landing_page#index', as: :landing_page_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/s' => 'homepage#index', as: :search_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/s' => 'homepage#index', as: :search_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  get '/' => 'homepage#index', as: :homepage_without_locale
  get '/:locale/s', to: redirect('/%{locale}', status: 307), constraints: { locale: locale_matcher }
  get '/s', to: redirect('/', status: 307)

  get '/500' => 'errors#server_error'
  get '/404' => 'errors#not_found', :as => :error_not_found
  get '/406' => 'errors#not_acceptable', :as => :error_not_acceptable
  get '/410' => 'errors#gone', as: :error_gone
  get '/community_not_found' => 'errors#community_not_found', as: :community_not_found

  resources :communities, only: [:new, :create]

  devise_for :people, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "sessions" }

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    put '/mercury_update' => "mercury_update#update", :as => :mercury_update

    get "/transactions/op_status/:process_token" => "transactions#paypal_op_status", as: :paypal_op_status
    get "/transactions/transaction_op_status/:process_token" => "transactions#transaction_op_status", :as => :transaction_op_status
    get "/transactions/created/:transaction_id" => "transactions#created", as: :transaction_created
    get "/transactions/finalize_processed/:process_token" => "transactions#finalize_processed", as: :transaction_finalize_processed

    get "/transactions/new" => "transactions#new", as: :new_transaction

    get "/listings/:listing_id/book", :to => redirect { |params, request|
      "/#{params[:locale]}/listings/#{params[:listing_id]}/initiate?#{request.query_string}"
    }
    post "/listings/:listing_id/booked"    => "preauthorize_transactions#initiated", as: :booked # POST request, no redirect

    get "/listings/:listing_id/initiate"   => "preauthorize_transactions#initiate", :as => :initiate_order
    post "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    post "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    get "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    get "/logout" => "sessions#destroy", :as => :logout
    get "/confirmation_pending" => "community_memberships#confirmation_pending", :as => :confirmation_pending
    get "/login" => "sessions#new", :as => :login
    get "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    get "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    get '/:person_id/settings/payments' => 'payment_settings#index', :as => :person_payment_settings
    post '/:person_id/settings/payments' => 'payment_settings#update', :as => :update_person_payment_settings
    get '/:person_id/settings/payments/paypal_account' => 'paypal_accounts#index', :as => :paypal_account_settings_payment

    get  '/community_memberships/pending_consent' => 'community_memberships#pending_consent', as: :pending_consent
    post '/community_memberships/give_consent'    => 'community_memberships#give_consent', as: :give_consent
    get  '/community_memberships/access_denied'   => 'community_memberships#access_denied', as: :access_denied

    get  '/community_memberships/check_email_availability_and_validity' => 'community_memberships#check_email_availability_and_validity'
    get  '/community_memberships/check_invitation_code'                 => 'community_memberships#check_invitation_code'

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do
      get '' => "getting_started_guide#index"
      
      resources :payment_preferences, only: [:index], param: :payment_gateway do
        collection do
          put :common_update
          put :update_stripe_keys
        end
        member do
          get :disable
          get :enable
        end
      end
      get  "/paypal_preferences" => redirect("/%{locale}/admin/payment_preferences")
      get  "/paypal_preferences/account_create"       => "paypal_preferences#account_create"
      get  "/paypal_preferences/permissions_verified" => "paypal_preferences#permissions_verified"
      
      get   "/settings" => "communities#settings",        as: :settings
      patch "/settings" => "communities#update_settings", as: :update_settings

      get "getting_started_guide"                        => "getting_started_guide#index",                  as: :getting_started_guide
      get "getting_started_guide/slogan_and_description" => "getting_started_guide#slogan_and_description", as: :getting_started_guide_slogan_and_description
      get "getting_started_guide/cover_photo"            => "getting_started_guide#cover_photo",            as: :getting_started_guide_cover_photo
      get "getting_started_guide/filter"                 => "getting_started_guide#filter",                 as: :getting_started_guide_filter
      get "getting_started_guide/payment"                => "getting_started_guide#payment",                as: :getting_started_guide_payment
      get "getting_started_guide/listing"                => "getting_started_guide#listing",                as: :getting_started_guide_listing
      get "getting_started_guide/invitation"             => "getting_started_guide#invitation",             as: :getting_started_guide_invitation

      get   "/look_and_feel/edit" => "communities#edit_look_and_feel",          as: :look_and_feel_edit
      patch "/look_and_feel"      => "communities#update_look_and_feel",        as: :look_and_feel
      get   "/details/edit"       => "community_customizations#edit_details",   as: :details_edit
      patch "/details"            => "community_customizations#update_details", as: :details
      get   "/new_layout"         => "communities#new_layout",                  as: :new_layout
      patch "/new_layout"         => "communities#update_new_layout",           as: :update_new_layout

      get   "/topbar/edit"        => "communities#topbar",                      as: :topbar_edit
      patch "/topbar"             => "communities#update_topbar",               as: :topbar

      get   "/landing_page"         => "communities#landing_page",                  as: :landing_page

      resources :communities do
        member do
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          delete :delete_marketplace

          get :topbar, to: redirect("/admin/topbar/edit")
          put :topbar, to: "communities#update_topbar" # PUT request, no redirect
          get :menu_links, to: redirect("/admin/topbar/edit")
          put :menu_links, to: "communities#update_topbar" # PUT request, no redirect

          get :getting_started, to: redirect('/admin/getting_started_guide')

          get :edit_details,       to: redirect("/admin/details/edit")
          put :update_details,     to: "community_customizations#update_details" # PUT request, no redirect

app/models/payment_settings.rb
# == Schema Information
#
# Table name: payment_settings
#
#  id                               :integer          not null, primary key
#  active                           :boolean          not null
#  community_id                     :integer          not null
#  payment_gateway                  :string(64)
#  payment_process                  :string(64)
#  commission_from_seller           :integer
#  minimum_price_cents              :integer
#  minimum_price_currency           :string(3)
#  minimum_transaction_fee_cents    :integer
#  minimum_transaction_fee_currency :string(3)
#  confirmation_after_days          :integer          not null
#  created_at                       :datetime         not null
#  updated_at                       :datetime         not null
#  api_client_id                    :string(255)
#  api_private_key                  :string(255)
#  api_publishable_key              :string(255)
#  api_verified                     :boolean
#  api_visible_private_key          :string(255)
#  api_country                      :string(255)
#
# Indexes
#
#  index_payment_settings_on_community_id  (community_id)
#

class PaymentSettings < ApplicationRecord

  validates_presence_of(:community_id)
end

app/views/payment_settings/_address_fields_form.haml
= fields_for stripe_account_form do |form|
  .row
    .col-12
      = form.label :address_line1, t("stripe_accounts.form_new.address_line1")+"*", class: 'required'
      = form.text_field :address_line1, class: 'required'
  .row.country-dependent{"data-country-except" => "IE"}
    .col-12
      = form.label :address_postal_code, t("stripe_accounts.form_new.address_postal_code")+"*"
      = form.text_field :address_postal_code, class: 'required'
  .row
    .col-12
      = form.label :address_city, t("stripe_accounts.form_new.address_city")+"*"
      = form.text_field :address_city, class: 'required'
  .row.country-dependent{"data-country-only" => "AU,IE,US,CA"}
    .col-12
      = form.label :address_state, t("stripe_accounts.form_new.address_state")+"*"
      = form.text_field :address_state

app/views/payment_settings/_bank_fields_form.haml
= fields_for stripe_bank_form do |form|
  .row.bank-routing-1.hidden
    .col-12
      = form.label :bank_routing_1, t("stripe_accounts.form_bank.bank_routing_1")+"*"
      = form.text_field :bank_routing_1, class: 'required'
  .row.bank-routing-2.hidden
    .col-12
      = form.label :bank_routing_2, t("stripe_accounts.form_bank.bank_routing_2")+"*"
      = form.text_field :bank_routing_2, class: 'required'
  .row.bank-routing-number.hidden
    .col-12
      = form.label :bank_routing_number, t("stripe_accounts.form_bank.bank_routing_number")+"*"
      = form.text_field :bank_routing_number, class: 'required'
  .row.bank-account-number
    .col-12
      = form.label :bank_account_number, t("stripe_accounts.form_bank.bank_account_number")+"*"
      = form.text_field :bank_account_number, class: 'required', value: stripe_seller_account[:bank_number_info] || form.object.bank_account_number
- content_for :extra_javascript do
  :javascript
    window.ST.stripe_form_i18n = #{I18n.t("stripe_accounts.form_bank.messages").to_json.html_safe};

app/views/payment_settings/_paypal_wizard.haml
- create_paypal_link = link_to(t("paypal_accounts.create_paypal_account_link_text"),
                               create_url, target: "_blank")
- upgrade_paypal_link = link_to(t("paypal_accounts.upgrade_paypal_account_link_text"),
                                upgrade_url, target: "_blank")
- paypal_redirect_link = "<a href='#' id='ask_paypal_permissions_redirect'>#{t("paypal_accounts.redirect_link_text")}</a>"

- if !@stripe_enabled
  = render partial: "paypal_accounts/paypal_info", locals: { create_paypal_account_link: create_paypal_link,
      upgrade_paypal_account_link: upgrade_paypal_link,
      paypal_account_linked: next_action != :ask_order_permission,
      receive_funds_info_label_tr_key: receive_funds_info_label_tr_key,
      receive_funds_info_tr_key: receive_funds_info_tr_key,
      commission_required: commission_type != :none }

- if next_action == :ask_order_permission
  - content_for :javascript do
    ST.initializeNewPaypalAccountHandler("ask_paypal_permissions", "#{order_permission_action}", ".js-paypal-redirect-order-permission");

  - if !@stripe_enabled
    .row.paypal-follow-steps
      .col-12
        = t("paypal_accounts.new.follow_steps")

  .row.paypal-wizard
    .col-12
      .paypal-wizard-content
        .row
          .col-12
            %h3.paypal-wizard-step
              =t("paypal_accounts.new.connect_paypal_account_title_with_step", current_step: 1, total_steps: 2)
        .row
          .col-12
            =t("paypal_accounts.new.connect_paypal_account_instructions")
        .row.send-button-wrapper.without-margin
          .col-12
            %button#ask_paypal_permissions
              = t("paypal_accounts.new.connect_paypal_account")
        .row.js-paypal-redirect-order-permission.hidden
          .col-12
            .paypal-redirect-message

              = t("paypal_accounts.redirect_message", redirect_link: paypal_redirect_link).html_safe
- elsif next_action == :ask_billing_agreement
  - content_for :javascript do
    ST.initializeNewPaypalAccountHandler("ask_billing_agreement", "#{billing_agreement_action}", ".js-paypal-redirect-billing-agreement");
    ST.initializeNewPaypalAccountHandler("ask_paypal_permissions", "#{order_permission_action}", ".js-paypal-redirect-change-account");
  - if commission_type != :none && !@stripe_enabled
    .row.paypal-follow-steps
      .col-12
        = t("paypal_accounts.new.follow_steps")

  .row.paypal-wizard
    .col-12
      - if !@stripe_enabled
        .paypal-wizard-content
          = render partial: "layouts/paypal_account_connected", locals: {paypal_account_email: paypal_account[:email],
              paypal_redirect_link: paypal_redirect_link}
        .paypal-wizard-divider
      - else
        .paypal-wizard-content
          =t("stripe_accounts.paypal_connected_give_permission", email: paypal_account[:email])

          .row.paypal-link-wrapper
            .col-12
              %a.paypal-change-link#ask_paypal_permissions
                = t("paypal_accounts.change_account")
        .paypal-wizard-divider

      .paypal-wizard-content
        .row
          .col-12
            %h3.paypal-wizard-step
              = t("paypal_accounts.new.paypal_account_billing_agreement_with_step", current_step: 2, total_steps: 2)
        .row
          .col-12
            - paypal_info_link = "<a id='paypal_fee_info_link' href='#'>#{t("paypal_accounts.new.paypal_info_link_text")}</a>"
            - if commission_type == :both # TODO: Tweak copy
              = render :partial => "layouts/info_text", :locals => {text: t("paypal_accounts.new.paypal_account_billing_agreement_info_both",
                commission_from_seller: commission_from_seller,
                minimum_commission: MoneyViewUtils.to_humanized(minimum_commission),
                paypal_info_link: paypal_info_link).html_safe }
            - elsif commission_type == :relative
              = render :partial => "layouts/info_text", :locals => {text: t("paypal_accounts.new.paypal_account_billing_agreement_info_relative",
                commission_from_seller: commission_from_seller,
                paypal_info_link: paypal_info_link).html_safe }
            - elsif commission_type == :fixed
              = render :partial => "layouts/info_text", :locals => {text: t("paypal_accounts.new.paypal_account_billing_agreement_info_fixed",
                minimum_commission: MoneyViewUtils.to_humanized(minimum_commission),
                paypal_info_link: paypal_info_link).html_safe }
            - else # no commission fee
              = render :partial => "layouts/info_text", :locals => {text: t("paypal_accounts.new.paypal_account_billing_agreement_info_none",
                paypal_info_link: paypal_info_link).html_safe }
        .row.send-button-wrapper.without-margin
          .col-12
            %button.send_button#ask_billing_agreement
              = t("paypal_accounts.new.billing_agreement")
        .row.js-paypal-redirect-billing-agreement.hidden
          .col-12
            .paypal-redirect-message
              - paypal_redirect_link = "<a href='#' id='ask_billing_agreement_redirect'>#{t("paypal_accounts.redirect_link_text")}</a>"
              = t("paypal_accounts.redirect_message", redirect_link: paypal_redirect_link).html_safe
        = render layout: "layouts/lightbox", locals: { id: "paypal_fee_info_content"} do
          %h2= t("common.paypal_fee_info.title")
          - text_with_line_breaks_html_safe do
            - link_to_paypal = link_to(t("common.paypal_fee_info.link_to_paypal_text"), paypal_fees_url, target: "_blank")
            = t("common.paypal_fee_info.body_text", link_to_paypal: link_to_paypal, paypal_commission: paypal_commission).html_safe

        - content_for :extra_javascript do
          :javascript
            $('#paypal_fee_info_link').click(function() { $('#paypal_fee_info_content').lightbox_me({centered: true, zIndex: 1000000}); });
- else

  - content_for :javascript do
    ST.initializeNewPaypalAccountHandler("ask_paypal_permissions", "#{order_permission_action}", ".js-paypal-redirect-change-account");
  - if !@stripe_enabled
    .row.paypal-wizard
      .col-12
        .paypal-wizard-content
          .row
            .col-12
              %h3.paypal-wizard-step-complete
                = t("paypal_accounts.paypal_account_all_set_up")
          .row
            .col-12
              =t("paypal_accounts.can_receive_payments")
          .row.paypal-first-steps-list
            .col-12
              =icon_tag("check", ["icon-fix", "paypal-success-mark"])
              =t("paypal_accounts.paypal_account_connected_summary", :email => paypal_account[:email])
          .row.paypal-last-steps-list
            .col-12
              =icon_tag("check", ["icon-fix", "paypal-success-mark"])
              =t("paypal_accounts.paypal_permission_granted_summary")
          .row.paypal-link-wrapper
            .col-12
              %a.paypal-change-link#ask_paypal_permissions
                = t("paypal_accounts.change_account")
          .row.hidden.js-paypal-redirect-change-account
            .col-12
              .paypal-redirect-message
                - paypal_redirect_link = "<a href='#' id='ask_paypal_permissions_redirect'>#{t("paypal_accounts.redirect_link_text")}</a>"
                = t("paypal_accounts.redirect_message", redirect_link: paypal_redirect_link).html_safe

app/views/payment_settings/_personal_id_number.haml
= fields_for stripe_account_form do |form|
  .row.country-dependent{"data-country-only" => "CA"}
    .col-12
      = label_tag :personal_id_number, t("stripe_accounts.form_pin.social_insurance_number")+"*"
      = form.text_field :personal_id_number, placeholder: '123456789', 'ca-social-insurance-number': true,
        data: {'msg-ca-social-insurance-number': t('stripe_accounts.form_pin.messages.social_insurance_number')}
  .row.country-dependent{"data-country-only" => "US"}
    .col-12
      = label_tag :personal_id_number, t("stripe_accounts.form_pin.social_security_number")+"*"
      = form.text_field :personal_id_number, placeholder: '123456789', required: true
  .row.country-dependent{"data-country-only" => "HK"}
    .col-12
      = label_tag :personal_id_number, t("stripe_accounts.form_pin.hong_kong_identity_card")+"*"
      = form.text_field :personal_id_number, placeholder: 'XY123456', required: true
  .row.country-dependent{"data-country-only" => "SG"}
    .col-12
      = label_tag :personal_id_number, t("stripe_accounts.form_pin.singapore_identity_card")+"*"
      = form.text_field :personal_id_number, placeholder: 'X1234567Y', required: true

app/views/payment_settings/_stripe_wizard.haml
- if stripe_account[:stripe_seller_id].present? 
  - if stripe_account[:stripe_bank_id].present?
    .row
      .col-12
        %h3.paypal-account-connected
          =icon_tag("check", ["icon-fix"])
          =t("stripe_accounts.stripe_bank_connected")
        %p
          =t("stripe_accounts.stripe_can_accept")

    .row
      = link_to t("stripe_accounts.form_new.edit"), "#", id: "edit-stripe-info"
  - elsif !paypal_enabled
    .row
      .col-12
        %h3= t("payment_settings.credit_card")
        %p 
          = t("payment_settings.credit_card_bank_details")
        %p
          = link_to t("payment_settings.add_bank_details"), '#', id: "edit-stripe-info"


  %div.hidden#stripe_forms
    .row.paypal-wizard.connect-row
      .col-12
        .paypal-wizard-content.connect-row
          = form_tag person_payment_settings_path(@current_user), id: "stripe-account-form", multipart: true do
            = hidden_field_tag "stripe_account_form_address_country", stripe_seller_account[:address_country]
            .row
              .col-12
                = label_tag t("stripe_accounts.form_new.legal_name")
                = stripe_seller_account[:legal_name]
            .row
              .col-12
                = label_tag t("stripe_accounts.form_new.country")
                = CountryI18nHelper.translate_country(stripe_seller_account[:address_country])

            = render partial: 'address_fields_form', locals: {stripe_account_form: stripe_address_form, available_countries: available_countries}

            = render partial: 'bank_fields_form', locals: {stripe_bank_form: stripe_bank_form, stripe_account: stripe_account, stripe_seller_account: stripe_seller_account, stripe_mode: stripe_mode}

            = render partial: 'verification_fields_form', locals: {stripe_verification_form: stripe_verification_form, seller_needs_verification: seller_needs_verification}

            .col-4
              = link_to t('stripe_accounts.form_new.cancel'), person_payment_settings_path(@current_user), style: 'float: right; margin-top: 1.5em'
              = button_tag t('stripe_accounts.form_new.save_details')
  - content_for :extra_javascript do
    :javascript
      $(function(){ 
      $("#edit-stripe-info").click(function(){
        $("#stripe_forms").toggleClass("hidden");
        $("#edit-stripe-info").hide();
        return false;
      });
      if(#{stripe_account[:stripe_bank_id].blank? || flash[:error].present?}) {
        $("#edit-stripe-info").hide();
        $("#stripe_forms").toggleClass("hidden");
      }})
- else
  %p
    = t("stripe_accounts.form_new.need_info")
  .row.paypal-wizard.connect-row
    %div
      .paypal-wizard-content.connect-row
        .col-12
          = form_tag person_payment_settings_path(@current_user), id: "stripe-account-form", multipart: true do
            = fields_for stripe_account_form do |form|
              .row
                .col-12
                  = form.error_messages
                  = form.label :legal_name, t("stripe_accounts.form_new.legal_name")+"*"
                  = form.text_field :legal_name, class: 'required'

              .row
                .col-12
                  = form.label :birth_date, t("stripe_accounts.form_new.birth_date")+"*"
                  = form.date_select :birth_date, {:start_year => Date.current.year-18, :end_year => 1920, order: [:day, :month, :year], :use_month_names => I18n.t("datepicker.months").values}, class: 'required'
              .row
                .col-2
                  = form.label :address_country, t("stripe_accounts.form_new.address_country")+"*"
                  = form.select :address_country, available_countries, {prompt: t("stripe_accounts.form_new.select_country")}, {style: "min-width: 200px"}

            .country-dependent{"data-country-except" => "XXX"}
              = render partial: 'address_fields_form', locals: {stripe_account_form: stripe_account_form, available_countries: available_countries}

            .country-dependent{"data-country-except" => "XXX"}
              = render partial: 'bank_fields_form', locals: {stripe_bank_form: stripe_bank_form, stripe_account: stripe_account, stripe_seller_account: stripe_seller_account, stripe_mode: stripe_mode}

            = render 'personal_id_number', stripe_account_form: stripe_account_form

            = render partial: 'verification_fields_form', locals: {stripe_verification_form: stripe_verification_form, seller_needs_verification: seller_needs_verification}

            .country-dependent{"data-country-except" => "XXX"}
              - base_terms_url = "https://stripe.com/COUNTRY/connect-account/legal#translation"
              - stripe_link = link_to t("stripe_accounts.form_new.tos_link_title"), base_terms_url, target: "_blank", data: {terms_url: base_terms_url}, id: "stripe-terms-link"
              = t("stripe_accounts.form_new.tos_link", stripe_link: stripe_link ).html_safe

              = button_tag t('stripe_accounts.form_new.save_details')

- content_for :extra_javascript do
  :javascript
    $(function() {
      window.ST.initStripeBankForm(#{!!stripe_test_mode});
    });

app/views/payment_settings/_verification_fields_form.haml
- if seller_needs_verification
  %h3
    = t("stripe_accounts.form_verification.need_verification")

  = fields_for :stripe_verification_form do |form|
    .row
      .col-12
        = label_tag :personal_id_number, t("stripe_accounts.form_verification.personal_id_number")
        = form.text_field :personal_id_number
    .row
      .col-12
        = label_tag :document, t("stripe_accounts.form_verification.document")
        = form.file_field :document

app/views/payment_settings/index.haml
- content_for :title_header do
  %h1= t("layouts.no_tribe.settings")

= render :partial => "layouts/left_hand_navigation", :locals => { :links => left_hand_navigation_links }

.left-navi-section.settings-section.payment-settings
  - if @stripe_enabled
    %h2= t("payment_settings.title")
  - else
    %h2= t("paypal_accounts.payout_info_title")

  - if @paypal_enabled && @stripe_enabled
    .row
      .col-12
        %p
          = t("payment_settings.can_accept_stripe_and_paypal")

    .row
      %div
        .col-12
          - if !seller_account.present? || !stripe_account[:stripe_bank_id].present?
            %h3= t("payment_settings.bank_account")
            %p
              = t("payment_settings.bank_account_details")
            - unless @stripe_error || seller_account.present?
              %p
                = link_to t("payment_settings.add_bank_details"), '#', id: "toggle_stripe_wizard"

          #stripe_wizard{class: @stripe_error || seller_account.present? ? "" : "hidden"}
            = render partial: "stripe_wizard", locals: local_assigns

          - if !paypal_account.present?
            %h3= t("payment_settings.paypal")
            %p
              = t("payment_settings.to_accept_paypal")
            %p
              = link_to t("payment_settings.connect_paypal"), '#', id: "toggle_paypal_wizard"
          - elsif next_action == :ask_billing_agreement
            %h3= t("payment_settings.paypal")
          - else
            %h3.paypal-account-connected
              =icon_tag("check", ["icon-fix"])
              =t("stripe_accounts.paypal_connected")
            %p
              =t("stripe_accounts.paypal_can_accept")

            .row.paypal-link-wrapper
              .col-12
                %a.paypal-change-link#ask_paypal_permissions
                  = t("paypal_accounts.change_account")

          #paypal_wizard{class: paypal_account.present? ? "" : "hidden"}
            = render partial: "paypal_wizard", locals: local_assigns

      - content_for :extra_javascript do
        :javascript
          $("#toggle_stripe_wizard").click(function(){$("#stripe_wizard").show(); $(this).hide(); return false;});
          $("#toggle_paypal_wizard").click(function(){$("#paypal_wizard").show(); $(this).hide(); return false;});

  - elsif @paypal_enabled
    = render partial: "paypal_wizard", locals: local_assigns

  - elsif @stripe_enabled
    = render partial: "stripe_wizard", locals: local_assigns