config/routes.rb
  get "/robots.txt" => RobotsGenerator

  get "/sitemap.xml.gz"                        => "sitemap#sitemap", format: :xml
  get "/sitemap/:sitemap_host/generate.xml.gz" => "sitemap#generate", format: :xml, :constraints => { sitemap_host: /[.\-\w]+/ }

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  get "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook
  post '/webhooks/plans' => 'plans#create'
  get '/webhooks/trials' => 'plans#get_trials'

  post '/bounces' => 'amazon_bounces#notification'

  get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  get "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  get "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    post "/prospect_emails" => "marketplaces#create_prospect_email"
  end

  match '/harmony_proxy/*harmony_path' => 'harmony_proxy#proxy', via: :all

  get "/ui_api/topbar_props" => "topbar_api#props"

  get '/_lp_preview' => 'landing_page#preview'

  locale_regex_string = Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES.to_a).join("|")
  locale_matcher = Regexp.new(locale_regex_string)
  locale_matcher_anchored = Regexp.new("^(#{locale_regex_string})$")

  get '/:locale/' => 'landing_page#index', as: :landing_page_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/' => 'landing_page#index', as: :landing_page_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/s' => 'homepage#index', as: :search_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/s' => 'homepage#index', as: :search_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  get '/' => 'homepage#index', as: :homepage_without_locale
  get '/:locale/s', to: redirect('/%{locale}', status: 307), constraints: { locale: locale_matcher }
  get '/s', to: redirect('/', status: 307)

  get '/500' => 'errors#server_error'
  get '/404' => 'errors#not_found', :as => :error_not_found
  get '/406' => 'errors#not_acceptable', :as => :error_not_acceptable
  get '/410' => 'errors#gone', as: :error_gone
  get '/community_not_found' => 'errors#community_not_found', as: :community_not_found

  resources :communities, only: [:new, :create]

  devise_for :people, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "sessions" }

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    put '/mercury_update' => "mercury_update#update", :as => :mercury_update

    get "/transactions/op_status/:process_token" => "transactions#paypal_op_status", as: :paypal_op_status
    get "/transactions/transaction_op_status/:process_token" => "transactions#transaction_op_status", :as => :transaction_op_status
    get "/transactions/created/:transaction_id" => "transactions#created", as: :transaction_created
    get "/transactions/finalize_processed/:process_token" => "transactions#finalize_processed", as: :transaction_finalize_processed

    get "/transactions/new" => "transactions#new", as: :new_transaction

    get "/listings/:listing_id/book", :to => redirect { |params, request|
      "/#{params[:locale]}/listings/#{params[:listing_id]}/initiate?#{request.query_string}"
    }
    post "/listings/:listing_id/booked"    => "preauthorize_transactions#initiated", as: :booked # POST request, no redirect

    get "/listings/:listing_id/initiate"   => "preauthorize_transactions#initiate", :as => :initiate_order
    post "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    post "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    get "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    get "/logout" => "sessions#destroy", :as => :logout
    get "/confirmation_pending" => "community_memberships#confirmation_pending", :as => :confirmation_pending
    get "/login" => "sessions#new", :as => :login
    get "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    get "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    get '/:person_id/settings/payments' => 'payment_settings#index', :as => :person_payment_settings
    post '/:person_id/settings/payments' => 'payment_settings#update', :as => :update_person_payment_settings
    get '/:person_id/settings/payments/paypal_account' => 'paypal_accounts#index', :as => :paypal_account_settings_payment

    get  '/community_memberships/pending_consent' => 'community_memberships#pending_consent', as: :pending_consent
    post '/community_memberships/give_consent'    => 'community_memberships#give_consent', as: :give_consent
    get  '/community_memberships/access_denied'   => 'community_memberships#access_denied', as: :access_denied

    get  '/community_memberships/check_email_availability_and_validity' => 'community_memberships#check_email_availability_and_validity'
    get  '/community_memberships/check_invitation_code'                 => 'community_memberships#check_invitation_code'

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do
      get '' => "getting_started_guide#index"
      
      resources :payment_preferences, only: [:index], param: :payment_gateway do
        collection do
          put :common_update
          put :update_stripe_keys
        end
        member do
          get :disable
          get :enable
        end
      end
      get  "/paypal_preferences" => redirect("/%{locale}/admin/payment_preferences")
      get  "/paypal_preferences/account_create"       => "paypal_preferences#account_create"
      get  "/paypal_preferences/permissions_verified" => "paypal_preferences#permissions_verified"
      
      get   "/settings" => "communities#settings",        as: :settings
      patch "/settings" => "communities#update_settings", as: :update_settings

      get "getting_started_guide"                        => "getting_started_guide#index",                  as: :getting_started_guide
      get "getting_started_guide/slogan_and_description" => "getting_started_guide#slogan_and_description", as: :getting_started_guide_slogan_and_description
      get "getting_started_guide/cover_photo"            => "getting_started_guide#cover_photo",            as: :getting_started_guide_cover_photo
      get "getting_started_guide/filter"                 => "getting_started_guide#filter",                 as: :getting_started_guide_filter
      get "getting_started_guide/payment"                => "getting_started_guide#payment",                as: :getting_started_guide_payment
      get "getting_started_guide/listing"                => "getting_started_guide#listing",                as: :getting_started_guide_listing
      get "getting_started_guide/invitation"             => "getting_started_guide#invitation",             as: :getting_started_guide_invitation

      get   "/look_and_feel/edit" => "communities#edit_look_and_feel",          as: :look_and_feel_edit
      patch "/look_and_feel"      => "communities#update_look_and_feel",        as: :look_and_feel
      get   "/details/edit"       => "community_customizations#edit_details",   as: :details_edit
      patch "/details"            => "community_customizations#update_details", as: :details
      get   "/new_layout"         => "communities#new_layout",                  as: :new_layout
      patch "/new_layout"         => "communities#update_new_layout",           as: :update_new_layout

      get   "/topbar/edit"        => "communities#topbar",                      as: :topbar_edit
      patch "/topbar"             => "communities#update_topbar",               as: :topbar

      get   "/landing_page"         => "communities#landing_page",                  as: :landing_page

      resources :communities do
        member do
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          delete :delete_marketplace

          get :topbar, to: redirect("/admin/topbar/edit")
          put :topbar, to: "communities#update_topbar" # PUT request, no redirect
          get :menu_links, to: redirect("/admin/topbar/edit")
          put :menu_links, to: "communities#update_topbar" # PUT request, no redirect

          get :getting_started, to: redirect('/admin/getting_started_guide')

          get :edit_details,       to: redirect("/admin/details/edit")
          put :update_details,     to: "community_customizations#update_details" # PUT request, no redirect
          get :edit_look_and_feel, to: redirect("/admin/look_and_feel/edit")

app/views/transactions/_details.haml
.message-avatar-padding
  .row
    .col-12

      %h2
        = link_to_unless listing[:deleted], listing[:title], listing_path(id: listing[:id])

      - if price_break_down_locals.present?
        = render partial: "transactions/price_break_down", locals: price_break_down_locals.merge(is_author: is_author)

      = render partial: "transactions/shipping_address", locals: { shipping_address: tx[:shipping_address] }

      %div{:id => "transaction_status"}
        = render :partial => "transactions/status/status", :locals => { :__transaction_model => transaction_model, role: role, is_author: is_author }

app/views/transactions/_price_break_down.haml
.initiate-transaction-totals
  - if booking
    .initiate-transaction-per-unit-wrapper
      %span.initiate-transaction-per-unit-label
        - if unit_type == :day
          = t("transactions.initiate.price_per_day")
        - else
          = t("transactions.initiate.price_per_night")
      %span.initiate-transaction-per-unit-value
        = MoneyViewUtils.to_humanized(listing_price)

    .initiate-transaction-booking-wrapper
      %span.initiate-transaction-booking-label
        - if unit_type == :day
          = use_new_translation("transactions.initiate.booked_days_label", count: duration).or_fallback_to("transactions.initiate.booked_days")
        - else
          = use_new_translation("transactions.initiate.booked_nights_label", count: duration).or_fallback_to("transactions.initiate.booked_nights")
      %span.initiate-transaction-booking-value
        = l start_on, format: :long_with_abbr_day_name
        = "-"
        - if unit_type == :day
          = l (end_on - 1.day), format: :long_with_abbr_day_name
          = "(#{pluralize(duration, t("listing_conversations.preauthorize.day"), t("listing_conversations.preauthorize.days"))})"
        - else
          = l end_on, format: :long_with_abbr_day_name
          = "(#{pluralize(duration, t("listing_conversations.preauthorize.night"), t("listing_conversations.preauthorize.nights"))})"

  - elsif quantity.present? && localized_unit_type.present?
    .initiate-transaction-per-unit-wrapper
      %span.initiate-transaction-per-unit-label
        = t("transactions.price_per_quantity", unit_type: localized_unit_type)
      %span.initiate-transaction-per-unit-value
        = MoneyViewUtils.to_humanized(listing_price)
    - if quantity > 1
      .initiate-transaction-quantity-wrapper
        %span.initiate-transaction-quantity-label
          = localized_selector_label || t("transactions.initiate.quantity")
        %span.initiate-transaction-quantity-value
          = quantity

  - if subtotal.present?
    .initiate-transaction-sum-wrapper
      %span.initiate-transaction-sum-label
        = t("transactions.initiate.subtotal")
      %span.initiate-transaction-sum-value
        = MoneyViewUtils.to_humanized(subtotal)

  - if shipping_price.present?
    .initiate-transaction-shipping-price-wrapper
      %span.initiate-transaction-shipping-price-label
        = t("transactions.initiate.shipping-price")
      %span.initiate-transaction-shipping-price-value
        = MoneyViewUtils.to_humanized(shipping_price)

  - if is_author
    .initiate-transaction-sum-wrapper
      %span.initiate-transaction-sum-label
        = t("transactions.total_to_pay")
      %span.initiate-transaction-sum-value
        = MoneyViewUtils.to_humanized(total)

    - if fee.present? && fee > 0
      .initiate-transaction-sum-wrapper
        %span.initiate-transaction-sum-label
          = t("conversations.accept.service_fee_label")
        %span.initiate-transaction-sum-value
          = "-#{MoneyViewUtils.to_humanized(fee)}"

  - if total.present?
    .initiate-transaction-total-wrapper
      %span.initiate-transaction-total-label
        - if total_label.present?
          = total_label
        - else
          = t("transactions.total")
      %span.initiate-transaction-total-value
        = MoneyViewUtils.to_humanized(is_author ? seller_gets : total)

app/views/transactions/_shipping_address.haml
- fields = [:name, :phone, :street1, :street2, :postal_code, :city, :state_or_province, :country]
- if shipping_address && shipping_address.slice(*fields).values.any?
  - shipping_address[:country] ||= CountryI18nHelper.translate_country(shipping_address[:country_code])
  .shipping-address-container
    %h2= t("shipping_address.shipping_address")
    - fields.map do |field|
      - if shipping_address[field].present?
        - if shipping_address[field] == :name
          .shipping-address-name= shipping_address[field]
        - else
          .shipping-address-row= shipping_address[field]

app/views/transactions/new.haml
- content_for :extra_javascript do
  :javascript
    ST.transaction.initializeFreeTransactionForm('#{I18n.locale}');

- content_for :title_header do
  %h1
    = action_button_label
    = link_to(listing[:title], listing_path(listing[:id]))

#new_message_form.centered-section

  - author_link = link_to(author[:display_name], person_path(username: author[:username]))

  .preauthorize-section
    %h2.preauthorize-details-title
      = t("listing_conversations.preauthorize.details")

    %ul.no-bullets
      %li
        %div
          = t("listing_conversations.preauthorize.by", listing: link_to("#{listing[:title]}", listing_path(listing[:id])), author: author_link).html_safe

      - m_price_break_down.each do |price_break_down|
        %li
          = render partial: "transactions/price_break_down", locals: price_break_down.merge(is_author: false)

  = form_tag(form_action, method: :post, id: "transaction-form") do

    = hidden_field_tag(:start_on, booking_start)
    = hidden_field_tag(:end_on, booking_end)


    .preauthorize-section
      %h2
        = t("conversations.new.send_message_to_user", person: author_link).html_safe
      .row
        .col-12
          = text_area_tag(:message, nil, :class => "text_area")

      - if quantity
        = hidden_field_tag(:quantity, quantity)

      .row
        .col-12
          = button_tag t("conversations.new.send_message"), :class => "send_button"

app/views/transactions/show.haml
= render :partial => "conversations/conversation_header", locals: {other_party: conversation_other_party}

.centered-section-wide
  = render :partial => "transactions/details", locals: {role: role, tx: transaction, transaction_model: transaction_model, listing: listing, is_author: is_author, price_break_down_locals: price_break_down_locals}

  = render :partial => "conversations/messages_and_form", locals: {role: role, message_form: message_form, message_form_action: message_form_action, messages: messages}